#!/usr/bin/env python3

import json
from urllib.request import urlopen, Request

with open("config.json") as file:
    config = json.load(file)

headers = {
    'Authorization': f"token {config['GHTOKEN']}",
     'Accept': 'application/vnd.github.v3+json'
}

url = f"https://api.github.com/orgs/{config['GHORG']}/repos?per_page=100"
httprequest = Request(url, headers=headers)

with urlopen(httprequest) as response:
    if response.status == 200:
        data = json.loads(response.read().decode())
        names = []
        for repo in data:
            names.append(repo['name'])
    else:
        print(f"Failed to fetch repos. Status code: {response.status_code}")

authors = {}
for name in names:
    url = f"https://api.github.com/repos/23W-GBAC/{name}/commits"
    print(f"Currently fetching commits for: {name}")
    httprequest = Request(url, headers=headers)
    with urlopen(httprequest) as response:
        if response.status == 200:
            data = json.loads(response.read().decode())
            author = data[0]['author']
            if author:
                authors[author['login']] = author
        else:
            print(f"Failed to fetch commits. Status code: {response.status_code}")

text = []
for author in authors.values():
    name = author['login']
    img = author['avatar_url']
    text.append(f"[![{name}]({img})]({url})")

result = " ".join(text)


with open('gallery.md', 'w') as file:
    file.write(result)
    print("All images written to gallery.md")
